"""Multi-platform Starlark helpers and template expansion rules for GNUstep Bazel builds."""

def _gnustep_expand_template_impl(ctx):
    out = ctx.actions.declare_file(ctx.attr.out)
    ctx.actions.expand_template(
        template = ctx.file.template,
        output = out,
        substitutions = ctx.attr.substitutions,
        is_executable = ctx.attr.is_executable,
    )
    return [DefaultInfo(files = depset([out]))]

gnustep_expand_template = rule(
    implementation = _gnustep_expand_template_impl,
    attrs = {
        "template": attr.label(allow_single_file = True, mandatory = True),
        "out": attr.string(mandatory = True),
        "substitutions": attr.string_dict(),
        "is_executable": attr.bool(default = False),
    },
)

def gnustep_target_copts():
    """Returns platform-specific GNUSTEP_TARGET_* compiler defines for Linux and FreeBSD (x86_64 and arm64)."""
    return select({
        Label("//bazel:linux_x86_64"): [
            "-DGNUSTEP_TARGET_DIR=\"x86_64/linux-gnu\"",
            "-DGNUSTEP_TARGET_CPU=\"x86_64\"",
            "-DGNUSTEP_TARGET_OS=\"linux-gnu\"",
        ],
        Label("//bazel:linux_arm64"): [
            "-DGNUSTEP_TARGET_DIR=\"aarch64/linux-gnu\"",
            "-DGNUSTEP_TARGET_CPU=\"aarch64\"",
            "-DGNUSTEP_TARGET_OS=\"linux-gnu\"",
        ],
        Label("//bazel:freebsd_x86_64"): [
            "-DGNUSTEP_TARGET_DIR=\"amd64/freebsd\"",
            "-DGNUSTEP_TARGET_CPU=\"amd64\"",
            "-DGNUSTEP_TARGET_OS=\"freebsd\"",
        ],
        Label("//bazel:freebsd_arm64"): [
            "-DGNUSTEP_TARGET_DIR=\"aarch64/freebsd\"",
            "-DGNUSTEP_TARGET_CPU=\"aarch64\"",
            "-DGNUSTEP_TARGET_OS=\"freebsd\"",
        ],
        "//conditions:default": [
            "-DGNUSTEP_TARGET_DIR=\"x86_64/linux-gnu\"",
            "-DGNUSTEP_TARGET_CPU=\"x86_64\"",
            "-DGNUSTEP_TARGET_OS=\"linux-gnu\"",
        ],
    })

def gnustep_platform_linkopts():
    """Returns OS-appropriate base linkopts for Linux and FreeBSD."""
    return select({
        Label("//bazel:os_freebsd"): [
            "-lpthread",
            "-lm",
            "-lc++",
        ],
        "//conditions:default": [
            "-lpthread",
            "-ldl",
            "-lm",
            "-lrt",
            "-lstdc++",
        ],
    })

def _make_sed_cmd(host, cpu, vendor, os_name):
    return " ".join([
        "-e 's|@configure_input@|Generated by Bazel|g'",
        "-e 's|@GNUSTEP_MAKE_VERSION@|2.9.3|g'",
        "-e 's|@GNUSTEP_MAKE_MAJOR_VERSION@|2|g'",
        "-e 's|@GNUSTEP_MAKE_MINOR_VERSION@|9|g'",
        "-e 's|@GNUSTEP_MAKE_SUBMINOR_VERSION@|3|g'",
        "-e 's|@GNUSTEP_CONFIG_FILE@|/etc/GNUstep/GNUstep.conf|g'",
        "-e 's|@GNUSTEP_USER_CONFIG_FILE@|.GNUstep.conf|g'",
        "-e 's|@GNUSTEP_MAKEFILES@|/usr/share/GNUstep/Makefiles|g'",
        "-e 's|@GNUSTEP_IS_FLATTENED@|yes|g'",
        "-e 's|@GNUSTEP_HOST@|" + host + "|g'",
        "-e 's|@GNUSTEP_HOST_CPU@|" + cpu + "|g'",
        "-e 's|@GNUSTEP_HOST_VENDOR@|" + vendor + "|g'",
        "-e 's|@GNUSTEP_HOST_OS@|" + os_name + "|g'",
        "-e 's|@clean_target_cpu@|" + cpu + "|g'",
        "-e 's|@clean_target_vendor@|" + vendor + "|g'",
        "-e 's|@clean_target_os@|" + os_name + "|g'",
        "-e 's|@ac_cv_library_combo@|ng-gnu-gnu|g'",
        "-e 's|@CC@|clang|g'",
        "-e 's|@CPP@|clang -E|g'",
        "-e 's|@CXX@|clang++|g'",
        "-e 's|@OBJCXX@|clang++|g'",
        "-e 's|@CPPFLAGS@||g'",
        "-e 's|@LDFLAGS@||g'",
        "-e 's|@EXEEXT@||g'",
        "-e 's|@DEBUGGER@|gdb|g'",
        "-e 's|@GNUMAKE@|make|g'",
    ])

def gnustep_make_sed_cmd(src_label, executable = False):
    """Returns a platform-aware genrule cmd for tools-make template substitution."""
    suffix = " $(location " + src_label + ") > $@" + (" && chmod +x $@" if executable else "")
    return select({
        Label("//bazel:linux_x86_64"): "sed " + _make_sed_cmd("x86_64-pc-linux-gnu", "x86_64", "pc", "linux-gnu") + suffix,
        Label("//bazel:linux_arm64"): "sed " + _make_sed_cmd("aarch64-unknown-linux-gnu", "aarch64", "unknown", "linux-gnu") + suffix,
        Label("//bazel:freebsd_x86_64"): "sed " + _make_sed_cmd("amd64-portbld-freebsd", "amd64", "portbld", "freebsd") + suffix,
        Label("//bazel:freebsd_arm64"): "sed " + _make_sed_cmd("aarch64-portbld-freebsd", "aarch64", "portbld", "freebsd") + suffix,
        "//conditions:default": "sed " + _make_sed_cmd("x86_64-pc-linux-gnu", "x86_64", "pc", "linux-gnu") + suffix,
    })
